### ISSUE TITLE
Create structure for 'Resources' Page

### ISSUE THREAD

**Issue by harisood** [uk-tre/hugo-website#4]
I’m struggling to think of a good way to structure the resources page - i.e. effectively signpost to resources so users can easily find and discover what they’re after. Current thoughts:
- Categorise by TYPE of resource (e.g. ‘code’, ‘paper’, ‘video’, ‘template’, ‘article’ etc)
  - Pros: Easy to categorise and a good first version
  - Cons: Not very discoverable, as e.g. papers could vary wildly in content (infrastructure design, approaches to sensitivity tiering, user experience…)
- Categorise by TOPIC of resource (e.g. ‘infastructure code’, ‘Toolkits and packages’, ‘information governance’, ‘accreditation’ etc)
  - Pros: Makes content more discoverable
  - Cons: Hard to know what the right categories will be. Also makes it more complicated from a data storage point of view for the website (e.g. multiple tags, more metadata, confusing hierarchies etc)

Any thoughts?

**Comment by harisood** [comment]
>  store the resources in a structured file (e.g. YAML)

I have a simple version of that atm but have also left room for MarkDown, e.g. https://github.com/uk-tre/hugo-website/blob/main/content/community_resources/code/turing_tre/index.md?plain=1

Would be up for going to purely YAML content and rendering templates, though it does make it possible sliiiightly more inaccessible (YAML configuration vs Markdown writing) for contributions

Either way the cataloguing issue still remains. Atm I am just using two different classes of tags but sure there's a better way!

@manics I also wonder if at some point it's worth us sitting down and going through the hugo architecture? Looks p much the same as Jekyll so shouldn't take too long?

**Comment by Davsarper** [comment]
Agreement on getting it done, and if there are issues in the future address them.

**Comment by harisood** [comment]
Happy with this as initial structure
